name: bs-framework
main: net.robbytu.banjoserver.framework.Main
version: ${version}
commands:
    bs-framework:
        description: bs-framework interaction
        permission:
        usage: /bs-framework
    spawn:
        description: Teleport to spawn
        permission:
        usage: /spawn
    ci:
        description: Clears your inventory
        permission:
        usage: /ci
        aliases: clearinventory
    time:
        description: Set the time
        permission:
        usage: /time [time]